#All utterances spoken by Cristopher in 20/01.cha from CHILDES New England corpus

#utt = [a.replace("*CHI:\t", "") for a in open("01.cha").read().split('\n') if a[:5] == "*CHI:"]
#childexemplars = dict((a,'') for a in set(utt))

#utt = [a.replace("*MOT:\t", "") for a in open("01.cha").read().split('\n') if a[:5] == "*MOT:"]
#motherexemplars = dict((a,'') for a in set(utt))

# (16 utterances by investigator ignored)
def getexemplars():
	c = childexemplars.items()
	m = motherexemplars.items()
	c = [(a,b) for a,b in c]
	m = [(a,b) for a,b in m]
	return dict(c + m)

childexemplars = {'&k .': '',
 '(..) yeah .': 'agreement',
 '+^ a cow !': 'assertion: animal(cow)',
 '+^ moo@o .': 'assertion: do(moo[1]) animal(cow)',
 '0 .': 'acknowledgement',
 '0 [<] .': 'acknowledgement',
 '0 [=! giggles] .': 'acknowledgement',
 '0 [=! grunt] .': 'acknowledgement',
 '0 [>] .': 'acknowledgement',
 '<tangle [?]> [<] .': '',
 'I want that [= object] .': 'assertion: want(X)',
 'Mama .': 'assertion: family(mother)',
 'Mommy .': 'assertion: family(mother)',
 'a ball .': 'assertion: toy(ball)',
 'animals .': 'assertion: animal(X) toy(book)',
 'apple .': 'assertion: point(apple) food(apple)',
 'awoh !': '',
 'baby .': 'assertion: family(baby)',
 'ball .': 'assertion: toy(ball)',
 'book .': 'assertion: toy(book)',
 'bowwow@c .': '',
 'box .': 'assertion: toy(box)',
 'box [>] .': 'assertion: toy(box)',
 'bunny .': 'assertion: animal(bunny)',
 'car .': 'assertion: vehicle(car)',
 'chairs .': 'assertion: furniture(chair)',
 'color .': 'assertion: draw(color)',
 'cow !': 'assertion: animal(cow)',
 'cow .': 'assertion: animal(cow)',
 'crayon .': 'assertion: toy(crayon)',
 'crayons .': 'assertion: toy(crayon)',
 'donkey .': 'assertion: animal(donkey)',
 'duck .': 'assertion: animal(duck)',
 'duckie .': 'assertion: animal(duck[0])',
 'egg .': 'assertion: animal(egg)',
 'fish .': 'assertion: animal(fish)',
 'fish [>] .': 'assertion: animal(fish)',
 'giraffe .': 'assertion: animal(giraffe)',
 'hat .': 'assertion: garment(hat)',
 'helicopter .': 'assertion: vehicle(helicopter)',
 'house .': 'assertion: point(house)',
 'ice+cream .': 'assertion: food(icecream)',
 'it hop .': 'assertion: do(hop) animal(bunny)',
 'kitty .': 'assertion: animal(cat[0])',
 'lion .': 'assertion: animal(lion[0])',
 'meow@o .': 'assertion: do(meow[0]) animal(cat)',
 'meow .': 'assertion: do(meow) animal(lion)',
 'no .': 'denial',
 'oh .': '',
 'open .': 'assertion: open(X)',
 'quack@o .': 'assertion: do(quack[0]) animal(duck)',
 'read it .': 'imperative: read(X)',
 'read it [= book] .': 'imperative: read(book)',
 'sheep .': 'assertion: animal(sheep)',
 'square .': 'assertion: shape(square)',
 'swing .': 'assertion: toy(swing)',
 'table .': 'assertion: furniture(table)',
 'that [= object] .': 'assertion: point(X)',
 'towel .': 'assertion: point(towel)',
 'tree .': 'assertion: point(tree)',
 'turtle .': 'assertion: animal(turtle)',
 'umbrella .': 'assertion: point(umbrella)',
 'want box .': 'assertion: want(box) toy(box)',
 'water .': 'assertion: point(water)',
 'xxx .': '',
 'xxx [<] .': '',
 'yeah .': 'agreement',
 'yyy !': '',
 'yyy .': '',
 'yyy wagon .': 'assertion: point(wagon) vehicle(wagon)'}

motherexemplars = { '+^ what does a bunny do ?': 'whquestion: do(X) animal(bunny)',
 '&k .': '',
 '+^ a gate ?': 'ynquestion: has(gate) family(grandma) garden(gate)',
 '+^ no touch .': 'imperative: notouch(slinky) toy(slinky)',
 "+^ what's this ?": 'whquestion: point(X) Y(X)',
 '0 .': '',
 '0 . [+ trn]': '',
 '0 [=! grunt] . [+ trn]': '',
 '<how (a)bout if I draw a circle this time> [>] ?': 'assertion: draw(circle) shape(circle)',
 '<is it [= object] nice> [<] ?': 'ynquestion: nice(X)',
 "<it's an orange> [>] .": 'assertion: point(orange) food(orange)',
 '<o:h> [>] .': '',
 '<this is an> [<] egg .': 'assertion: point(egg) animal(egg)',
 '<what a pretty picture> [>] .': 'assertion: pretty(picture) point(picture)',
 '<what does a duckie say> [>] ?': 'whquestion: do(X) animal(duck[3])',
 '<with a tingle tangle [>] <tit mouse robin mows great eggs> [?] >': '',
 'Chris Chris .': 'imperative: attention',
 'a baby sheep is a lamb .': 'assertion: baby(lamb) animal(sheep)',
 'a lambie .': 'assertion: point(lamb) animal(lamb[1])',
 'a square .': 'assertion: point(square) shape(square)',
 'a@l .': '',
 'ah !': '',
 'airplane .': 'assertion: point(airplane) vehicle(airplane)',
 'awoh .': '',
 'book [=! whispers] .': 'assertion: point(book)',
 'box (.) yeah .': 'reinforcement: shape(box)',
 'can you catch ?': 'imperative: catch(X) toy(X)',
 'can you catch [>] ?': 'imperative: catch(X) toy(X)',
 'can you make that little man pop up ?': 'imperative: pop(man) toy(jackinthebox)',
 'can you open it [= box] ?': 'imperative: open(box) toy(box)',
 'can you throw it [= ball] to Mommy ?': 'imperative: throw(X) toy(X) family(mommy)',
 'do you have one of these [= jack+in+the+box] ?': 'assertion: point(jackinthebox) toy(jackinthebox)',
 'do you know who he is ?': 'whquestion: point(X) person(X)',
 'do you want me to draw anything [>] ?': 'ynquestion: draw(X)',
 'do you want to look at another box ?': 'ynquestion: look(box) toy(box)',
 "doesn't Grammy have one of those at her house ?": 'ynquestion: has(X) family(grandma[1])',
 'giraffe .': 'assertion: point(giraffe) animal(giraffe)',
 'he [= clown] pops up .': 'assertion: point(clown) pop(clown) toy(jackinthebox)',
 'hmm ?': '',
 'honey no touch xxx .': 'imperative: notouch(X)',
 'hop .': 'assertion: do(hop) animal(bunny)',
 'how (a)bout a square ?': 'ynquestion: shape(square) draw(square)',
 'is it [= object] pretty ?': 'ynquestion: pretty(X)',
 'is that <a rabbit> [//] a bunny ?': 'ynquestion: point(bunny) animal(bunny)',
 'is that Mommy ?': 'ynquestion: point(mother) family(mother[2])',
 'is that [= object] pretty ?': 'ynquestion: pretty(X)',
 'is that a bear ?': 'assertion: point(bear) animal(bear)',
 'is that a cow ?': 'assertion: point(cow) animal(cow)',
 'is that a donkey ?': 'assertion: point(donkey) animal(donkey)',
 'is that a kangaroo ?': 'assertion: point(kangaroo) animal(kangaroo)',
 'is that a table ?': 'assertion: point(table) furniture(table)',
 "is that the baby's mommy ?": 'assertion: point(mother) family(baby)',
 'is this the same as that [= jack+in+the+box] ?': 'ynquestion: toy(jackinthebox)',
 "isn't it [= object] <pretty &n> [>] ?": 'ynquestion: pretty(X)',
 "isn't it [= object] pretty ?": 'ynquestion: pretty(X)',
 "it's a xylophone .": 'assertion: point(xylophone) music(xylophone)',
 "it's kind o(f) like an apple though .": 'assertion: like(apple) food(apple)',
 'jack+in+the+box ?': 'assertion: toy(jackinthebox)',
 'just look okay .': 'imperative: look(X)',
 'let go let go .': 'imperative: letgo(X)',
 "let's <put (th)em [= papers] back> [>] .": 'imperative: putback(papers)',
 'look .': 'imperative: look(X)',
 'no .': 'denial',
 'no ?': 'ynquestion',
 'no hands .': 'imperative: notouch(X)',
 'no hands okay honey ?': 'imperative: notouch(X)',
 'no no .': 'denial',
 'no you want that crayon ?': 'ynquestion: want(crayon) toy(crayon)',
 'no+no .': 'denial',
 'oh (.) put everything away ?': 'ynquestion: putback(X)',
 'oh .': '',
 'oh [=! laughs] ice cream .': 'assertion: point(icecream) food(icecream)',
 "oh isn't that [= CHI's paper] nice .": 'assertion: nice(X)',
 'oh look !': 'imperative: look(X)',
 'oh you want another box ?': 'ynquestion: want(box) toy(box)',
 'oh you want me to color .': 'ynquestion: draw(color)',
 'oh you want me to use the orange one [= crayon] now .': 'ynquestion: draw(orange)',
 'okay .': 'acknowledgement',
 'okay ?': 'ynquestion',
 'okay well Mommy will color too .': 'assertion: draw(color)',
 'oops .': '',
 'open it [= box] up .': 'imperative: open(box) toy(box)',
 'peekaboo !': '',
 'put everything back in the box .': 'imperative: putback(X) toy(box)',
 'put it [= crayon] away .': 'imperative: putback(X)',
 'put it [= crayon] away okay .': 'imperative: putback(X)',
 'right .': 'reinforcement',
 'right here .': 'assertion: point(X)',
 'say byebye .': 'imperative: say(bye)',
 "see the birdie's eggs ?": 'assertion: point(egg) bird(egg)',
 'thank+you .': '',
 'that [//] this is a fish .': 'assertion: point(fish) animal(fish)',
 "that's a bowwow@c that's right .": 'reinforcement',
 "that's a donkey .": 'assertion: point(donkey) animal(donkey)',
 "that's a good boy .": 'reinforcement',
 "that's a hat .": 'assertion: point(hat) garment(hat)',
 "that's a mother .": 'assertion: point(mother) family(mother)',
 "that's a nest .": 'assertion: point(nest) animal(nest)',
 "that's a swing .": 'assertion: point(swing) toy(swing)',
 "that's a wagon !": 'assertion: point(wagon) vehicle(wagon)',
 "that's a xylophone .": 'assertion: point(xylophone) music(xylophone)',
 "that's an elephant .": 'assertion: point(elephant) animal(elephant)',
 "that's an umbrella .": 'assertion: point(umbrella)',
 "that's not a helicopter .": 'denial: point(X) vehicle(helicopter)',
 "that's not a turtle (.) that's a nest .": 'denial: point(nest) animal(turtle)',
 "that's right .": 'reinforcement',
 "that's somebody's back yard .": 'assertion: point(backyard)',
 "that's the cow .": 'assertion: point(cow) animal(cow)',
 "that's the lion .": 'assertion: point(lion) animal(lion)',
 "that's where a birdie lives is in a nest .": 'assertion: point(nest) animal(bird)',
 'this is Santa Claus .': 'assertion: point(santa) person(santa)',
 'this is a gate .': 'assertion: point(gate) garden(gate)',
 'this is a lamb .': 'assertion: point(lamb) animal(lamb)',
 'this is a sheep .': 'assertion: point(sheep) animal(sheep)',
 'this is a truck .': 'assertion: point(truck) vehicle(truck)',
 'this is a violin .': 'assertion: point(violin) music(violin)',
 'those are chairs +...': 'assertion: point(chair) furniture(chair)',
 'towel ?': 'ynquestion: point(towel)',
 'truck ?': 'assertion: point(truck) vehicle(truck)',
 'want the other box [=! whispers] ?': 'ynquestion: want(box) toy(box)',
 'we gonna [: going to] put this [= cloth] away ?': 'ynquestion: putback(X)',
 'we have to put our toys away .': 'imperative: putback(X) toy(X)',
 'we just look .': 'imperative: notouch(X)',
 "we'll put that box +...": 'assertion: toy(box)',
 'well we have to put this [= cloth] away right ?': 'assertion: putback(X)',
 'what [>] ?': 'whquestion',
 'what are you going to do ?': 'whquestion: do(X)',
 'what do you want me to color ?': 'ynquestion: want(color) draw(color)',
 'what does a cow say ?': 'whquestion: do(X) animal(cow)',
 'what does a lion say ?': 'whquestion: do(X) animal(lion)',
 'what else is in the box ?': 'whquestion: inside(X) toy(box)',
 'what is [!] it ?': 'whquestion: point(X) Y(X)',
 'what would you like me to color ?': 'ynquestion: want(color) draw(color)',
 "what's a kitty say ?": 'whquestion: do(X) animal(cat[2])',
 "what's in the book ?": 'whquestion: inside(X) toy(book)',
 "what's in this box ?": 'whquestion: inside(X) toy(box)',
 "what's inside ?": 'whquestion: inside(X) toy(box)',
 "what's it [= object] ?": 'whquestion: point(X) Y(X)',
 "what's that ?": 'whquestion: point(X) Y(X)',
 "what's this ?": 'whquestion: point(X) Y(X)',
 "what's this though (.) here [>] ?": 'whquestion: point(X) Y(X)',
 "what's this though ?": 'whquestion: point(X) Y(X)',
 "where's Christopher ?": '',
 "who's this ?": 'whquestion: point(X) person(X)',
 'wow [=! whispered] .': '',
 'xxx .': '',
 'yeah .': 'acknowledgement',
 "you can't touch .": 'imperative: notouch(X)',
 'you have one of those [= xylophone] .': 'assertion: has(xylophone) music(xylophone)',
 'you just have to look .': 'imperative: look(X)',
 'you ready ?': '',
 'you want another box ?': 'ynquestion: want(box) toy(box)',
 'you want me to read it [= book] ?': 'ynquestion: read(book)',
 'you want that box ?': 'ynquestion: want(box) toy(box)',
 'you want you +...': '',
 'you were afraid of him last year .': 'assertion: afraid(X) person(X)',
 "you're gonna [: going to] color ?": 'assertion: draw(color)'}
